name: Salesforce Code Analyzer Workflow
on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        required: true
        type: string

jobs:
  salesforce-code-analyzer-workflow:
    permissions:
      pull-requests: write # Grants permission to create a pull request review. Only necessary if running against pull requests.
      contents: read # Grants permission to check out the repository. Only necessary for private repos.
      actions: read # Grants permission to read the in-progress actions. Only necessary for private repos.
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          ref: ${{ inputs.BRANCH_NAME }}

      # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v5
        with:
          node-version: '>=20.9.0'
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v5
        with:
          java-version: '>=11'
          distribution: 'zulu'
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.10'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest

      # - name: Get changed files
      #   id: changed
      #   run: |
      #     git fetch origin ${{ github.base_ref }} --depth=1

      #     RAW_CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD || true)
      #     echo "Raw changed files:"
      #     echo "$RAW_CHANGED_FILES"

      #     CHANGED_FILES_BY_TYPE=$(echo "$RAW_CHANGED_FILES" | grep -E '\.(cls|trigger|html|htm|xhtml|xht|shtml|cmp|js|cjs|mjs|ts|page|component|xml)$' || true)
      #     echo "Changed files by type:"
      #     echo "$CHANGED_FILES_BY_TYPE"
          
      #     CHANGED_FILES=$(echo "$CHANGED_FILES_BY_TYPE" | grep -E 'force-app' || true)
      #     echo "Changed files:"
      #     echo "$CHANGED_FILES"
          
      #     TARGET_ARGS=$(echo "$CHANGED_FILES" | sed 's/^/--target \"/g' | sed 's/$/"/g' || true)
      #     TARGET_ARGS=$(echo $TARGET_ARGS)
      #     echo "Computed target arguments:"
      #     echo "$TARGET_ARGS"

      #     echo "target=$TARGET_ARGS" >> $GITHUB_OUTPUT
      #     echo "changed_files<<EOF" >> $GITHUB_OUTPUT
      #     echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
      #     echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Salesforce Code Analyzer on changed files
        if: steps.changed.outputs.changed_files != ''
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json --severity-threshold 2
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}

      # Only fail the build if there are sev 2 or above violation, for sev 3 or below fail if it exceed the main branch pmd violation as of 2025-11-05
      # - name: Check the Outputs to Determine Whether to Fail
      #   if: |
      #     steps.run-code-analyzer.outputs.exit-code > 0 ||
      #     steps.run-code-analyzer.outputs.num-sev3-violations > 4414 ||
      #     steps.run-code-analyzer.outputs.num-sev4-violations > 5413 ||
      #     steps.run-code-analyzer.outputs.num-sev5-violations > 0
      #   run: exit 1
